<<<<<<< HEAD
# Generated by Django 2.1.5 on 2022-03-08 15:29

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 2.1.5 on 2022-03-07 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> d5702fed5616aeca894bddbe8eb01dd00495a6be


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryID', models.IntegerField(max_length=128)),
                ('countryname', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
=======
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
>>>>>>> d5702fed5616aeca894bddbe8eb01dd00495a6be
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('festivalID', models.IntegerField(max_length=128)),
                ('festivalname', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField()),
                ('countryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Country')),
            ],
            options={
                'verbose_name_plural': 'Festivals',
            },
=======
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='festival.Story'),
>>>>>>> d5702fed5616aeca894bddbe8eb01dd00495a6be
        ),
    ]
