# Generated by Django 2.1.5 on 2022-03-15 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.IntegerField(unique=True)),
                ('commentMessage', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('datePosted',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryID', models.IntegerField(default=0)),
                ('countryname', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivalID', models.IntegerField(default=0)),
                ('festivalname', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
                ('image_url', models.URLField(default='spring.jpg')),
                ('countryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyID', models.IntegerField(unique=True)),
                ('storyMessage', models.TextField()),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('festivalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ('datePosted',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='StoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Story'),
        ),
    ]
