# Generated by Django 2.1.5 on 2022-03-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryID', models.IntegerField(max_length=128)),
                ('countryname', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivalID', models.IntegerField(max_length=128)),
                ('festivalname', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField()),
                ('countryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Country')),
            ],
            options={
                'verbose_name_plural': 'Festivals',
            },
        ),
    ]
