# Generated by Django 2.1.5 on 2022-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countryID',
            field=models.IntegerField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festivalID',
            field=models.IntegerField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festivalname',
            field=models.CharField(max_length=128),
        ),
    ]
